# Generated by Django 5.2.17 on 2026-09-15 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('games', '0001_initial'),
        ('patients', '0003_patientprofile_accessibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='clinical.clinicalnote'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='status_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='category',
            field=models.CharField(choices=[('cognitive', 'Cognitive'), ('medication', 'Medication'), ('mood', 'Mood'), ('sleep', 'Sleep'), ('routine', 'Routine'), ('general', 'General'), ('caregiver_feedback', 'Caregiver feedback'), ('observation', 'Observation'), ('follow_up', 'Follow-up')], max_length=32),
        ),
        migrations.CreateModel(
            name='ClinicalBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnoses', models.TextField(blank=True)),
                ('assessment_scores', models.JSONField(blank=True, default=list)),
                ('visual_limits', models.TextField(blank=True)),
                ('motor_limits', models.TextField(blank=True)),
                ('ideal_session_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_difficulty_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_baseline', to='patients.patientprofile')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DdaOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('set_level', 'Set level'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('cap', 'Cap')], max_length=16)),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamedefinition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_level', models.PositiveSmallIntegerField()),
                ('target_minutes', models.PositiveSmallIntegerField()),
                ('times_per_week', models.PositiveSmallIntegerField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=16)),
                ('review_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamedefinition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_assignments', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['review_date', 'id'],
            },
        ),
    ]
