# Generated by Django 5.2.17 on 2026-09-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_clinicalnote_follow_up_date_clinicalnote_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalbaseline',
            name='allergies',
            field=models.TextField(blank=True),
        ),
    ]
