# Generated by Django 5.2.17 on 2026-09-14 07:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_key', models.CharField(choices=[('no_login_2d', 'No login for two days'), ('missed_meds_3in7', 'Three missed medicines in seven days'), ('level_drop_x3', 'Three difficulty level drops'), ('reaction_time_worsening', 'Reaction time worsening'), ('engagement_drop', 'Engagement drop'), ('low_mood_3d', 'Low mood for three days'), ('sos', 'SOS'), ('pin_lockout', 'Patient PIN locked'), ('device_offline_3d', 'Device offline for three days')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('attention', 'Attention'), ('high', 'High')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('forwarded', 'Forwarded'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_alerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-triggered_at', 'id'],
                'indexes': [models.Index(fields=['patient', 'status'], name='alert_patient_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('patient', 'rule_key'), name='unique_open_patient_rule_alert')],
            },
        ),
    ]
