# Generated by Django 5.2.17 on 2026-09-14 19:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
        ("patients", "0003_patientprofile_accessibility_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SosEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_updated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("triggered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("location_text", models.CharField(blank=True, max_length=255)),
                ("notified", models.JSONField(default=list)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_sos_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_events",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at", "id"],
            },
        ),
    ]
