# Generated by Django 5.2.17 on 2026-09-16 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0005_alter_alert_rule_key"),
        ("patients", "0005_favourites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="rule_key",
            field=models.CharField(
                choices=[
                    ("no_login_2d", "No login for two days"),
                    ("missed_meds_3in7", "Three missed medicines in seven days"),
                    ("level_drop_x3", "Three difficulty level drops"),
                    ("reaction_time_worsening", "Reaction time worsening"),
                    ("engagement_drop", "Engagement drop"),
                    ("low_mood_3d", "Low mood for three days"),
                    ("sos", "SOS"),
                    ("pin_lockout", "Patient PIN locked"),
                    ("device_offline_3d", "Device offline for three days"),
                    ("prescription_updated", "Prescription updated"),
                    ("pin_reset_request", "PIN reset request"),
                    ("checkin_help", "Check-in help requested"),
                    ("sync_error", "Device sharing error"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CheckInResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_updated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "answer",
                    models.CharField(
                        choices=[("okay", "Okay"), ("need_help", "Need help")], max_length=16
                    ),
                ),
                ("responded_at", models.DateTimeField()),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="alerts.checkin",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "in_app"),
                            ("email", "email"),
                            ("push", "push"),
                            ("sms", "sms"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "rule_key",
                    models.CharField(
                        choices=[
                            ("no_login_2d", "No login for two days"),
                            ("missed_meds_3in7", "Three missed medicines in seven days"),
                            ("level_drop_x3", "Three difficulty level drops"),
                            ("reaction_time_worsening", "Reaction time worsening"),
                            ("engagement_drop", "Engagement drop"),
                            ("low_mood_3d", "Low mood for three days"),
                            ("sos", "SOS"),
                            ("pin_lockout", "Patient PIN locked"),
                            ("device_offline_3d", "Device offline for three days"),
                            ("prescription_updated", "Prescription updated"),
                            ("pin_reset_request", "PIN reset request"),
                            ("checkin_help", "Check-in help requested"),
                            ("sync_error", "Device sharing error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "channel", "rule_key"),
                        name="unique_user_channel_rule_preference",
                    )
                ],
            },
        ),
    ]
