# Generated by Django 5.2.17 on 2026-09-14 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_patientprofile_accessibility_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("dose", models.CharField(max_length=128)),
                ("times", models.JSONField(default=list)),
                ("instructions", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("flag_for_caregiver", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("later", "Later"),
                            ("skipped", "Skipped"),
                            ("help", "Help"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_reminders",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReminderResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("later", "Later"),
                            ("skipped", "Skipped"),
                            ("help", "Help"),
                        ],
                        max_length=16,
                    ),
                ),
                ("responded_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                ("idempotency_key", models.UUIDField(unique=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="routines.reminder",
                    ),
                ),
            ],
            options={
                "ordering": ["responded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoutineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine"),
                            ("water", "Water"),
                            ("meal", "Meal"),
                            ("doctor_visit", "Doctor visit"),
                            ("game", "Game"),
                            ("walk", "Walk"),
                            ("call", "Call"),
                            ("sleep", "Sleep"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("time_of_day", models.TimeField()),
                ("days_of_week", models.JSONField(default=list)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("caregiver", "Caregiver"),
                            ("doctor", "Doctor"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_ref", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_items",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["time_of_day", "id"],
            },
        ),
        migrations.AddField(
            model_name="reminder",
            name="routine_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="routines.routineitem",
            ),
        ),
    ]
