# Generated by Django 5.2.17 on 2026-09-14 19:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routineitem_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='routineitem',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
