# Generated by Django 5.2.17 on 2026-09-16 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_favourites"),
        ("routines", "0004_alter_routineitem_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_updated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("logged_at", models.DateTimeField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("ok", "Ok"),
                            ("low", "Low"),
                            ("bad", "Bad"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("patient", "Patient"), ("caregiver", "Caregiver")], max_length=16
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_logs",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SleepLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_updated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("date", models.DateField()),
                ("bed_time", models.TimeField()),
                ("wake_time", models.TimeField()),
                ("quality", models.PositiveSmallIntegerField(default=3)),
                (
                    "source",
                    models.CharField(
                        choices=[("patient", "Patient"), ("caregiver", "Caregiver")], max_length=16
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_logs",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
