# Generated by Django 5.2.17 on 2026-09-16 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("tts_locale", models.CharField(blank=True, max_length=20)),
                ("font_family", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("place", "Place"),
                            ("festival", "Festival"),
                            ("dish", "Dish"),
                            ("tune", "Tune"),
                            ("activity", "Activity"),
                            ("sound", "Sound"),
                            ("word", "Word"),
                            ("routine_scene", "Routine scene"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_translations", models.JSONField(blank=True, default=dict)),
                ("image", models.ImageField(blank=True, upload_to="content/images/%Y/%m/")),
                ("audio", models.FileField(blank=True, upload_to="content/audio/%Y/%m/")),
                ("tags", models.JSONField(blank=True, default=dict)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_content_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_items",
                        to="content.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region__name", "kind", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "kind", "title"), name="unique_content_title"
                    )
                ],
            },
        ),
    ]
