# Generated by Django 5.2.17 on 2026-09-14 16:55

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_careassignment_assigned_by_careassignment_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='accessibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='challenge_mode_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='cultural_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='favourite_songs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='happy_things',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='hobbies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='home_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='known_places',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='life_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='max_difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='session_cap_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='soothing_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='work_history',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ConsentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_memories_with_doctor', models.BooleanField(default=False)),
                ('use_memories_in_quiz', models.BooleanField(default=False)),
                ('share_mood_with_doctor', models.BooleanField(default=False)),
                ('share_audio_with_doctor', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='patients.patientprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['patient__user__username'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('daughter', 'Daughter'), ('son', 'Son'), ('spouse', 'Spouse'), ('grandchild', 'Grandchild'), ('friend', 'Friend'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=32)),
                ('relationship_label', models.CharField(blank=True, max_length=128)),
                ('photo', models.ImageField(blank=True, upload_to='family/%Y/%m/')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
