# Generated by Django 5.2.17 on 2026-09-14 19:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0003_patientprofile_accessibility_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Memory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("festival", "Festival"),
                            ("wedding", "Wedding"),
                            ("trip", "Trip"),
                            ("daily", "Everyday moment"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_on", models.DateField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("quiz", "Quiz"),
                            ("care_team", "Care team"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="patients.patientprofile",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True, related_name="memories", to="patients.familymember"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MemoryMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video"), ("audio", "Audio")],
                        default="photo",
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(upload_to="memories/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "memory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="memories.memory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MemoryQuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_updated_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("who", "Who"),
                            ("when", "When"),
                            ("where", "Where"),
                            ("occasion", "Occasion"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expected", models.CharField(max_length=255)),
                ("given", models.CharField(max_length=255)),
                ("correct", models.BooleanField()),
                ("attempted_at", models.DateTimeField()),
                ("response_ms", models.PositiveIntegerField()),
                (
                    "memory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="memories.memory",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-attempted_at", "id"],
            },
        ),
    ]
