# Generated by Django 5.2.17 on 2026-09-17 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="memory",
            managers=[],
        ),
    ]
