# Generated by Django 5.2.17 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0003_devicesession")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("as", "Assamese"), ("bn", "Bengali")],
                default="en",
                max_length=8,
            ),
        ),
    ]
