# Generated by Django 5.2.17 on 2026-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_add_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('as', 'Assamese'), ('bn', 'Bengali'), ('hi', 'Hindi'), ('te', 'Telugu'), ('mni', 'Manipuri'), ('lus', 'Mizo')], default='en', max_length=8),
        ),
    ]
