# Generated by Django 5.2.17 on 2026-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedefinition',
            name='regions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
