# Generated by Django 5.2.17 on 2026-09-17 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_integrated_games"),
        ("patients", "0005_favourites"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePerformanceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.UUIDField()),
                ("performance", models.JSONField()),
                ("decision", models.JSONField(default=dict)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.gamedefinition"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="patients.patientprofile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
