# Generated by Django 5.2.17 on 2026-09-17 18:41

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.models.functions import Least


def bound_live_levels(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for name, fields in [
        ("GameDefinition", ["max_level"]),
        ("DifficultyState", ["level", "cap_level"]),
    ]:
        model = apps.get_model("games", name)
        for field in fields:
            model.objects.filter(**{field + "__gt": 5}).update(**{field: Least(field, 5)})
    # Historical sessions and clinician audit records remain intact.


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_gameperformanceevent"),
    ]

    operations = [
        migrations.RunPython(bound_live_levels, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="gamedefinition",
            name="max_level",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
