"""Build original illustrative practice packs, never impersonating reviewed photos/music."""
import csv
import hashlib
import html
import json
import math
from pathlib import Path
import struct
import wave

ROOT = Path(__file__).resolve().parents[1]
PLACES = ['Riverbank', 'Village market', 'Tea garden path', 'Hill viewpoint', 'Lake shore', 'Community courtyard', 'Village bridge', 'School garden', 'Bus stop', 'Post office', 'Local library', 'Rice field', 'Flower garden', 'Bamboo grove', 'Walking path', 'Family home', 'Neighbourhood shop', 'Community hall', 'Playground', 'Shaded bench']
FESTIVALS = ['Festival flowers', 'Festival drum', 'Decorated courtyard', 'Celebration lamp', 'Family gathering', 'Harvest basket', 'Welcome garland', 'Community dance']
DISHES = ['Rice bowl', 'Tea cup', 'Vegetable stew', 'Fruit plate', 'Bread basket', 'Sweet rice', 'Lentil bowl', 'Soup cup', 'Banana snack', 'Steamed vegetables']
WORDS = ['Cup', 'Kettle', 'Basket', 'Book', 'Chair', 'Table', 'Lamp', 'Clock', 'Key', 'Door', 'Window', 'Umbrella', 'Hat', 'Bag', 'Spoon', 'Bowl', 'Plate', 'Bottle', 'Leaf', 'Flower', 'Tree', 'Sun', 'Moon', 'Star', 'Cloud', 'Rain', 'Bird', 'Fish', 'Butterfly', 'Boat', 'Bridge', 'House', 'Drum', 'Bell', 'Ball', 'Kite', 'Banana', 'Mango', 'Apple', 'Rice']
ACTIVITIES = {
    'Making tea': ['Fill the kettle', 'Boil the water', 'Add tea leaves', 'Pour into a cup', 'Let it cool', 'Sit comfortably', 'Enjoy the tea'],
    'Packing a picnic': ['Choose a basket', 'Pack clean plates', 'Add fruit', 'Add bread', 'Fill a water bottle', 'Close the basket', 'Carry the basket'],
    'Watering a plant': ['Find the watering can', 'Fill it with water', 'Walk to the plant', 'Water the soil', 'Let the water soak', 'Put the can away', 'Enjoy the plant'],
    'Setting the table': ['Clear the table', 'Wipe the surface', 'Put down plates', 'Add spoons', 'Add cups', 'Bring the food', 'Sit together'],
    'Getting ready for a walk': ['Check the weather', 'Choose comfortable clothes', 'Put on shoes', 'Take a water bottle', 'Tell a family member', 'Open the door', 'Walk slowly'],
    'Putting away shopping': ['Place bags on the table', 'Take out the fruit', 'Put fruit in a bowl', 'Store the rice', 'Store the vegetables', 'Fold the bags', 'Wash your hands'],
}
TUNES = ['Rising chime', 'Falling chime', 'Gentle alternating tones', 'Three-note practice', 'Four-note practice']
SOUNDS = ['Soft bell tone', 'Low bell tone', 'High chime', 'Gentle alternating tones', 'Rising tones', 'Falling tones', 'Three-note signal', 'Two-tone signal']
SCENES = ['Garden courtyard', 'Market courtyard', 'Lakeside path', 'Home courtyard', 'Community courtyard']
REGIONS = ['AS', 'ML', 'AR', 'MN', 'MZ', 'NL', 'SK', 'TR']
ATTRIBUTION = 'Original Smarana geometric illustration / synthesized practice audio, generated by the repository script. CC0-1.0. Generic English demo content; not documentary photos or traditional recordings.'


def illustration(title, kind, region):
    value = int(hashlib.sha256(title.encode()).hexdigest()[:8], 16)
    color = '#447b62' if region == 'AS' else '#536c9b'
    hue = value % 360
    if kind in {'place', 'routine_scene'}:
        graphic = f'<circle cx="250" cy="65" r="25" fill="#f5cd65"/><path d="M0 180L85 75L160 180L220 100L320 180V250H0Z" fill="{color}"/><path d="M0 210Q100 170 180 220T320 200V260H0Z" fill="#72b9cc"/><rect x="45" y="140" width="55" height="48" rx="4" fill="#ecd6aa"/><path d="M35 140L72 110L110 140Z" fill="#946955"/><rect x="67" y="158" width="12" height="30" fill="#765a42"/><path d="M245 175V130" stroke="#765a42" stroke-width="10"/><circle cx="245" cy="120" r="28" fill="#84ad6a"/>'
    elif kind == 'dish':
        graphic = f'<ellipse cx="160" cy="195" rx="112" ry="28" fill="#d5dfd1"/><path d="M75 115H245Q240 190 160 195Q80 190 75 115" fill="{color}"/><ellipse cx="160" cy="115" rx="85" ry="30" fill="#f8e7b3"/>' + ''.join(f'<circle cx="{95+i*25}" cy="{110+(i%2)*12}" r="12" fill="hsl({(hue+i*25)%360} 55% 65%)"/>' for i in range(6))
    elif kind in {'sound', 'tune'}:
        graphic = ''.join(f'<rect x="{55+i*24}" y="{120-(i%3)*20}" width="12" height="{40+(i%3)*40}" rx="6" fill="{color}"/>' for i in range(9))
    else:
        # A clear card symbol with distinct geometry, color and label; English
        # labels are part of the practice illustration, not native translations.
        graphic = f'<rect x="72" y="62" width="176" height="140" rx="28" fill="hsl({hue} 40% 76%)" stroke="{color}" stroke-width="6"/><path d="M110 165L160 90L210 165Z" fill="{color}"/><circle cx="160" cy="132" r="18" fill="#fff6dd"/>'
    safe = html.escape(title)
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="320" height="300" viewBox="0 0 320 300"><rect width="320" height="300" rx="20" fill="#f6f3ea"/>{graphic}<text x="160" y="280" text-anchor="middle" font-family="sans-serif" font-size="15" fill="#243b32">{safe}</text></svg>'


def write_audio(path, index):
    rate = 16000
    frames = bytearray()
    for n in range(rate * 3):
        t = n / rate
        envelope = max(0, 1 - (t % .6) / .5) * .2
        frequency = [262, 330, 392, 440, 523][(int(t * 2) + index) % 5]
        value = math.sin(2 * math.pi * frequency * t) * envelope
        frames.extend(struct.pack('<h', int(value * 32767)))
    with wave.open(str(path), 'wb') as output:
        output.setparams((1, 2, rate, 0, 'NONE', 'not compressed'))
        output.writeframes(frames)


def change_scene(count):
    names = ['Flower', 'Bird', 'Basket', 'Lamp']
    shapes = ['<circle cx="70" cy="150" r="23" fill="#df87a9"/><circle cx="70" cy="150" r="10" fill="#f5cc56"/>', '<path d="M140 150 q20 -40 40 0 q20 20 40 0 q-30 45 -80 0" fill="#487dba"/>', '<path d="M250 130 h50 l-5 45 h-40z" fill="#be9050"/>', '<rect x="345" y="120" width="30" height="50" rx="8" fill="#f7cf6a"/>']
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 430 240"><rect width="430" height="240" fill="#e9f2e8"/><path d="M0 200 Q200 160 430 200 V240 H0" fill="#94bc7e"/>' + ''.join(shapes[count:]) + ''.join(f'<text x="{[70,180,275,360][index]}" y="220" text-anchor="middle" font-size="16">{name}</text>' for index,name in enumerate(names) if index>=count) + '</svg>'


def main():
    packs = {}
    for region in REGIONS:
        folder = ROOT / 'backend' / 'content' / region
        public = ROOT / 'frontend' / 'public' / 'content' / 'demo' / region
        folder.mkdir(parents=True, exist_ok=True)
        public.mkdir(parents=True, exist_ok=True)
        items = {}
        rows = []
        kinds = {'place': PLACES, 'festival': FESTIVALS, 'dish': DISHES, 'tune': TUNES, 'sound': SOUNDS, 'activity': list(ACTIVITIES), 'word': WORDS, 'routine_scene': SCENES}
        for kind, titles in kinds.items():
            selected = (titles[:4] if kind == 'routine_scene' else titles) if region in {'AS', 'ML'} else titles[:5]
            if kind == 'activity' and region == 'ML': selected = list(reversed(selected))
            for index, title in enumerate(selected):
                if kind == 'festival':
                    title = f'{["Spring", "Summer", "Autumn", "Winter"][index % 4]} practice celebration {index+1}'
                slug = f'{kind}-{index+1}'
                image_name = f'{slug}.svg'
                svg = illustration(title, kind, region)
                (folder / f'{slug}.svg').write_text(svg)
                (public / f'{slug}.svg').write_text(svg)
                tags = {'generic': True, 'demo': True, 'note': f'Illustrative practice: {title.lower()}.', 'attribution': ATTRIBUTION}
                if kind == 'tune': tags['notes'] = 'C,D,E,G,A,B,D,F' if region == 'AS' else 'G,E,D,C,F,A,B,D'
                if kind == 'festival':
                    tags.update(season=['Spring','Summer','Autumn','Winter'][index % 4], month=['April','July','October','January'][index % 4], state=region)
                if kind == 'routine_scene':
                    tags['targets'] = ['flower', 'bird', 'basket', 'leaf', 'bench', 'lamp']
                    tags['distractors'] = ['cloud', 'stone', 'path', 'fence', 'hat', 'door', 'tree', 'window']
                    image_name = f'change-{index+1}-original.svg'
                    (folder / image_name).write_text(change_scene(0))
                    (public / image_name).write_text(change_scene(0))
                    tags['variants'] = []
                    for count in range(1, 5):
                        variant = f'change-{index+1}-{count}.svg'
                        (public / variant).write_text(change_scene(count))
                        tags['variants'].append({'imageUrl': f'/content/demo/{region}/{variant}', 'differences': [{'id': name.lower(), 'title': name, 'imageUrl': ''} for name in ['Flower', 'Bird', 'Basket', 'Lamp'][:count]]})
                if kind == 'activity':
                    tags['steps'] = []
                    for step, label in enumerate(ACTIVITIES[title]):
                        name = f'{slug}-step-{step+1}.svg'
                        step_svg = illustration(label, 'word', region)
                        (folder / name).write_text(step_svg)
                        (public / name).write_text(step_svg)
                        tags['steps'].append({'id': f'{slug}:{step}', 'title': label, 'imageUrl': f'/content/demo/{region}/{name}'})
                audio = ''
                if kind in {'tune', 'sound'}:
                    audio = f'{slug}.wav'
                    write_audio(folder / audio, index)
                    (public / audio).write_bytes((folder / audio).read_bytes())
                rows.append({'kind': kind, 'title': title, 'image': image_name, 'audio': audio, 'attribution': ATTRIBUTION, 'generic': 'true', 'tags': json.dumps(tags)})
                items.setdefault(kind, []).append({'id': f'demo:{region}:{slug}', 'title': title, 'image_url': f'/content/demo/{region}/{image_name}', 'audio_url': f'/content/demo/{region}/{audio}' if audio else None, 'tags': tags})
        with (folder / 'manifest.csv').open('w', newline='') as output:
            writer = csv.DictWriter(output, lineterminator="\n", fieldnames=['kind', 'title', 'image', 'audio', 'attribution', 'generic', 'tags'])
            writer.writeheader(); writer.writerows(rows)
        packs[region] = {'version': 'original-demo-v1', 'region': region, 'items': items}
    (ROOT / 'frontend' / 'src' / 'content' / 'demo-packs.json').write_text(json.dumps(packs, indent=2)+'\n')


if __name__ == '__main__':
    main()
